### ISSUE TITLE
Cocaine::CommandNotFoundError

### ISSUE THREAD

**Issue by thomaswelton** [cnorthwood/eurovisionhue#6]
Thanks for the update but now get this

```bundle exec ruby eurovisionhue.rb
Detected change to Sweden on the live blog
/Users/carolineinnes/.rvm/gems/ruby-2.1.0/gems/cocaine-0.5.8/lib/cocaine/command_line.rb:82:in `run': Cocaine::CommandNotFoundError (Cocaine::CommandNotFoundError)
	from /Users/carolineinnes/.rvm/gems/ruby-2.1.0/gems/miro-0.4.0/lib/miro/dominant_colors.rb:84:in `downsample_colors_and_convert_to_png!'
	from /Users/carolineinnes/.rvm/gems/ruby-2.1.0/gems/miro-0.4.0/lib/miro/dominant_colors.rb:73:in `extract_colors_from_image'
	from /Users/carolineinnes/.rvm/gems/ruby-2.1.0/gems/miro-0.4.0/lib/miro/dominant_colors.rb:47:in `sorted_pixels'
	from /Users/carolineinnes/.rvm/gems/ruby-2.1.0/gems/miro-0.4.0/lib/miro/dominant_colors.rb:19:in `to_rgb'
	from eurovisionhue.rb:64:in `block in <main>'
	from eurovisionhue.rb:62:in `each'
	from eurovisionhue.rb:62:in `each_with_index'
	from eurovisionhue.rb:62:in `<main>'```

**Comment by cnorthwood** [comment]
I think you may need ImageMagick installed to make Miro work: https://www.imagemagick.org/script/binary-releases.php. I shall update the docs

**Comment by thomaswelton** [comment]
Image magick seemd to have fixed it but now getting

**Comment by thomaswelton** [comment]
```Detected change to Sweden on the live blog
Transitioning Bed Lights to [0, 37, 99]
Transitioning Ceiling 1 to [252, 155, 0]
Transitioning Ceiling 3 to [34, 72, 33]
Transitioning Chest of draws to [88, 99, 13]
Transitioning Wardrobe to [108, 107, 9]
eurovisionhue.rb:65:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from eurovisionhue.rb:62:in `each'
	from eurovisionhue.rb:62:in `each_with_index'
	from eurovisionhue.rb:62:in `<main>'
```

**Comment by cnorthwood** [comment]
Ah, I wonder if that happens if you have more lights than there are colours in the flag :/ sorry, I only have 2 to test with

**Comment by okko** [comment]
A workaround is to make a group fo the lights that should be controlled, and then patch
https://github.com/cnorthwood/eurovisionhue/blob/master/eurovisionhue.rb#L69 to
```
    group = hue.group(8)
    group.lights.each_with_index do |light, i|
```

where `8` is the index for that group.

**Comment by RobertCain** [comment]
@thomaswelton This was happening to me to. I've done a quick fix for this and it's just been merged.  

It reduces the chance of it occurring by allowing colours to be re-used twice. The error might still occur if you have a lot of bulbs.

**Comment by thomaswelton** [comment]
Thanks
